apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: drone
spec:
  updateStrategy:
    type: RollingUpdate
  serviceName: drone
  template:
    metadata:
      labels:
        app: drone
        project: telephoneorg
        environment: production
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: ci-server
                operator: In
                values:
                - 'true'
      containers:
      - name: docker
        image: docker:dind
        imagePullPolicy: IfNotPresent
        args:
        - --storage-driver=overlay2
        volumeMounts:
        - name: var-run
          mountPath: /var/run
        securityContext:
          privileged: true
      - name: server
        image: drone/drone:0.7
        env:
        - name: DRONE_OPEN
          valueFrom:
            configMapKeyRef:
              name: drone
              key: drone.open
        - name: DRONE_HOST
          valueFrom:
            configMapKeyRef:
              name: drone
              key: drone.host
        - name: DRONE_GITHUB
          valueFrom:
            configMapKeyRef:
              name: drone
              key: github
        - name: DRONE_GITHUB_CLIENT
          valueFrom:
            configMapKeyRef:
              name: drone
              key: github.client
        - name: DRONE_ORGS
          valueFrom:
            configMapKeyRef:
              name: drone
              key: drone.orgs
        - name: DRONE_ADMIN
          valueFrom:
            configMapKeyRef:
              name: drone
              key: drone.admin
        - name: DRONE_GITHUB_SECRET
          valueFrom:
            secretKeyRef:
              name: drone
              key: github.secret
        - name: DRONE_SECRET
          valueFrom:
            secretKeyRef:
              name: drone
              key: drone.secret
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: drone-data
          mountPath: /var/lib/drone
      - name: agent
        image: drone/drone:0.7
        args:
        - agent
        env:
        - name: DRONE_SERVER
          valueFrom:
            configMapKeyRef:
              name: drone
              key: drone.server
        - name: DRONE_SECRET
          valueFrom:
            secretKeyRef:
              name: drone
              key: drone.secret
        volumeMounts:
        - name: var-run
          mountPath: /var/run
      volumes:
      - name: var-run
        emptyDir:
          medium: Memory
  volumeClaimTemplates:
  - metadata:
      name: drone-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
